name: Malini
styles: [
  "Regular",
  "Black",
  "Thin",
  "Oblique",
  "Oblique-Thin",
  "Condensed",
  "Expanded",
  "Display",
  "Thin-Display",
  "Text"
]
version: 1.000
unitsPerEm: 1000
ascender: 750
xheight: 465
mheight: 465
Xheight: 705
descender: 250
source: https://gitlab.com/smc/fonts/Malini
author:
  name: Santhosh Thottingal
  email: santhosh.thottingal@gmail.com
  url: https://thottingal.in
license:
  text: "This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: https://openfontlicense.org"
  url: https://openfontlicense.org
manufacturer:
  name: SMC
  url: https://smc.org.in
sources: sources
build: fonts
proofs: proofs
tests: tests
glyphs:
  classes:
    LC_ALL: abcdefghijklmnopqrstuvwxyz
    UC_ALL: ABCDEFGHIJKLMNOPQRSTUVWXYZ
    LATIN_EXTRA: [
      "Á","Ǽ","Â","Ä","À","Ā","Å","Ã","Ǎ","Ă", "Ą",
      "Ć","Č","Ç","Ĉ","Ċ",
      "Ď",
      "É","Ě","Ê","Ë","Ė","È","Ē", "Ę",
      "Ĝ","Ġ","Ģ", "Ğ",
      "Ĥ",
      "Í","Î","Ï","Ì","Ī","Ĩ", "Į", "İ",
      "Ĵ",
      "Ķ",
      "Ĺ", "Ļ", "Ľ",
      "Ń","Ň","Ñ","Ņ",
      "Ó","Ô","Ö","Ò","Ō","Õ", "Ő",
      "Ŕ","Ř","Ŗ",
      "Ś","Š","Ş","Ŝ", "Ș",
      "̆̆Ť", "Ț", "Ť",
      "Ú","Ǔ","Û","Ü","Ù","Ū","Ů","Ũ","Ų", "Ű", "Ŭ",
      "Ŵ","Ẁ","Ẃ","Ẅ",
      "Ý","Ŷ","Ỳ","Ÿ",
      "Ž","Ż","Ź",
      "á","ǽ","â","ä","à","ā","å","ã","̆ă", "ą", "ă", "ǎ",
      "ć","č","ç","ĉ","ċ",
      "ď",
      "é","ě","ê","ë","ė","è","ē", "ę",
      "ĝ","ġ","ğ", "ģ",
      "ĥ",
      "í","î","ï","ì","ī","ĩ", "į",
      "ĵ", "ǰ",
      "ķ",
      "ĺ", "ļ", "ľ",
      "ń","ň","ñ", "ņ",
      "ó","ǒ","ô","ö","ò","ō","õ", "ő",
      "ŕ","ř", "ŗ",
      "ś","š","ş","ŝ", "ș",
      "ť", "ț",
      "ú","ǔ","û","ü","ù","ū","ů","ũ", "ŭ", "ų", "ű",
      "ŵ","ẃ", "ẁ", "ẅ",
      "ý","ŷ","ÿ", "ỳ",
      "ź","ž","ż",
    ]
    LATIN_LIGATURES:  [ "tt", "ff", "ft", "fi", "ij" ] # [ "ffi", "th", ]
    ML_CONSONANTS: കഖഗഘങചഛജഝഞടഠഡഢണതഥദധനപഫബഭമയരലവറശഷസഹളഴ
    ML_VOWEL_SIGNS: ['ാ', 'ി','ീ', "ു", "ൂ", "ൃ", "ൄ", "ൢ", "ൣ", "െ", "േ", "ൈ", "ൊ", "ോ","ൌ", "ൗ"]
    ML_VOWEL_SIGNS_CONJOINING: ["ു", "ൂ", "ൃ", "ൄ", "ൢ", "ൣ"]
    ML_I_SIGNS: ['ി','ീ']
    ML_CONS_CONJUNCTS: ["ക്ക", "ക്ഷ", "ഗ്ഗ", "ഗ്ദ", "ഗ്ദ്ധ", "ഗ്ന", "ഗ്മ", "ങ്ങ", "ക്ത", "ങ്ക", "ക്ട", "ക്റ്റ",
                     "ച്ച", "ച്ഛ", "ജ്ജ", "ഞ്ച", "ഞ്ജ", "ജ്ഞ", "ഞ്ഞ",
                     "ട്ട", "ണ്ണ", "ണ്ഡ", "ണ്ട", "ണ്മ", "ണ്ഠ", "ഡ്ഡ", "ഡ്ഢ",
                     "ത്ത", "ത്ഥ", "ത്ന", "ത്ഭ", "ദ്ദ", "ദ്ധ", "ന്ന", "ത്സ", "ത്മ", "ന്ത", "ന്ഥ", "ന്ദ", "ന്ധ", "ന്മ", "ന്റ", "ൻ്റ",
                     "പ്പ", "പ്ഫ", "ബ്ബ", "ബ്ദ", "മ്മ", "മ്പ", "പ്ന", "പ്ത", "പ്റ്റ", "ഫ്റ്റ",
                     "യ്യ", "യ്ക","യ്ക്ക", "യ്ത",
                     "ല്ല", "ല്പ",
                     "വ്വ",
                     "ശ്ച", "ശ്ശ", "ശ്ന",
                     "സ്സ", "സ്റ്റ", "സ്ഥ", "സ്ക", "സ്ക്ക", "സ്ത", "സ്ന", "സ്പ",
                     "ഷ്ക", "ഷ്ക്ക", "ഷ്ട", "ഷ്ഠ", "ഷ്പ",
                     "ഹ്ന", "ഹ്മ",
                     "ള്ള", "റ്റ"]
    ML_REPH_CONJUNCTS: ["ക്ര", "ക്ക്ര", "ക്ത്ര", "ഗ്ര", "ഗ്ദ്ധ്ര", "ഘ്ര", "ങ്ക്ര",
                     "ഛ്ര", "ജ്ര", "ഝ്ര",
                     "ട്ര", "ഡ്ര", "ഢ്ര", "ണ്ട്ര",
                     "ത്ര", "ത്ത്ര", "ത്സ്ര",
                     "ദ്ര", "ധ്ര", "ന്ത്ര", "ന്ദ്ര", "ന്ധ്ര", "ദ്ധ്ര", "ന്ര",
                     "പ്ര", "ഫ്ര", "ബ്ര", "ഭ്ര", "മ്ര", "മ്പ്ര",
                     "വ്ര", "ശ്ര", "സ്ര", "സ്ത്ര",
                     "ഹ്ര", "ഷ്ര", "ഷ്ട്ര", "റ്റ്ര"]
    ML_PREVENT_CONJUNCTS: ["ക്റ്റു", "ക്റ്റൂ",
                     "ക്ടു", "ക്ടൂ", "ക്ടൃ",
                     "ഗ്ഗു", "ഗ്ഗൂ",
                     "ച്ഛു", "ച്ഛൂ",
                     "ത്ഭൂ", "ല്പു", "ല്പൂ", "ഷ്പു","ഷ്പൂ",
                     "ത്നു", "ത്നൂ", "ക്തു", "ക്തൂ",
                     "ണ്ഠു", "ണ്ഠൂ",
                     "ഡ്ഡു", "ഡ്ഡൂ",  "ഡ്ഢു","ഡ്ഢൂ",
                     "പ്നു","പ്നൂ", "പ്റ്റു", "ഫ്റ്റു", "പ്റ്റൂ", "ഫ്റ്റൂ",
                     "പ്തു", "പ്തൂ",
                     "ബ്ദു", "ബ്ദൂ",
                     "യ്കു", "യ്കൂ", "യ്ക്കു", "യ്ക്കൂ", "യ്തു", "യ്തൂ",
                     "സ്കു", "സ്കൂ",
                     "സ്ക്കു", "സ്ക്കൂ",
                     "സ്തു","സ്തൂ", "സ്ത്രു","സ്ത്രൂ", "സ്നു", "സ്നൂ", "സ്റ്റു","സ്റ്റൂ",
                     "സ്പു", "സ്പൂ",
                     "ശ്നു", "ശ്നൂ",
                     "ഷ്കു", "ഷ്കൂ",
                     "ഷ്ക്കു","ഷ്ക്കൂ",
                     "ഷ്ടു", "ഷ്ടൂ", "ഷ്ട്രു", "ഷ്ട്രൂ",
                     "ഷ്ഠു", "ഷ്ഠൂ"
                    ]
    ML_LA_CONJUNCTS: ["ക്ല", "ഗ്ല", "ത്ല", "പ്ല", "ഫ്ല", "ബ്ല", "മ്ല", "വ്ല", "സ്ല", "ശ്ല", "ഹ്ല"]
    ML_TOP_MARKS: ["ൎ", "ഀ"]
    ML_BOTTOM_MARKS: [ "ൢ", "ൣ"]

  # Kern pairs
  kern:
    classes:
      # Lower cases
      # Pair - Left
      1.a: a
      1.c: c
      1.f: ["f", "ff"]
      1.g: g
      1.r: r
      1.rounds: opbe
      1.k: k
      1.j: j
      1.t: ["t","tt"]
      1.v: vwy
      1.verticals_lower: imnquh
      1.verticals_tall: dl
      1.z: z

      # Pair - Right
      2.a: a
      2.f: ["f", "ff"]
      2.i: i
      2.j: j
      2.r: r
      2.rounds: ["e", "ee", "c", "d", "q", "g", "o"]
      2.s: s
      2.t: ["t","tt"]
      2.u: u
      2.x: x
      2.v: vwy
      2.verticals_tall: bl
      2.verticals: ["m", "n", "p"]

      # Upper cases
      1.A: AÆ
      1.B: B
      1.C: C
      1.F: F
      1.G: G
      1.K: K
      1.L: L
      1.P: P
      1.ROUNDS: OQD
      1.S: S
      1.T: T
      1.U: U
      1.V: VYW
      1.X: X

      2.A: AÆ
      2.J: J
      2.PARANTHESIS: "()"
      2.QUOTES: ["'","\"","‘","’","“","”"]
      2.ROUNDS: CGOQ
      2.S: S
      2.T: T
      2.V: VYW
      2.X: X

    latin: # script

      - ["1.verticals_lower", "2.v", -40] #  hy hv hw, uv nv dy
      - ["1.verticals_tall", "2.v", -40] #  lv, dv dy
      - ["1.r", "2.rounds", -10] #  ro re
      - ["1.v", "2.rounds", -30]
      - ["1.v", "2.verticals_tall", -40] # vl vb
      - ["1.v", "2.s", -40]
      - ["1.a", "2.t", -10]
      - ["1.a", "2.v", -40]

      - ["1.c", "2.v", -40]  #  cv

      - ["1.f", "2.f", -10] #  ff
      - ["1.f", "2.rounds", -40] #  fo
      - ["1.f", "2.u", -40] #  fu
      - ["1.f", "2.a", -20] #  fa
      - ["1.i", "2.v", -40] #  iv
      - ["1.f", "2.r", -20] #  fr
      - ["1.f", "2.v", -60]
      - ["1.f", "2.verticals", -40]
      - ["1.f", "2.i", -80]
      - ["1.f", "2.z", -60]

      - ["1.g", "2.j", 120] # gj
      - ["1.g", "2.s", -50] # fs

      - ["1.j", "2.j", 80] # jj

      - ["1.t", "2.t", -20]
      - ["1.t", "2.v", -40]  #  tv, ty,tw

      - ["1.A", "2.u", -40]  #  Au
      - ["1.A", "2.t", -40]  #  At
      - ["1.A", "2.T", -100]  #  At
      - ["1.A", "2.V", -100]  #  Av Ay
      - ["1.A", "2.v", -80]  #  Av Ay
      - ["1.A", "2.ROUNDS", -50]  #  AO AC

      - ["1.B", "2.V", -70]  #  BV

      - ["1.C", "2.v", -50]  #  Cv
      - ["1.C", "2.V", -70]  #  CV

      - ["1.F", "2.rounds", -40]  #  Fo
      - ["1.F", "2.A", -100]  #  FA
      - ["1.F", "2.a", -40]  #  Fa
      - ["1.F", "2.J", -100]  #  FJ

      - ["1.G", "2.v", -40]  #  Gv Gy
      - ["1.G", "2.V", -70]  #  GV GY
      - ["1.G", "2.X", -60]  #  GV GY

      - ["1.K", "2.rounds", -50]  #  Ko Ke
      - ["1.K", "2.u", -60]  #  Ku
      - ["1.K", "2.v", -100]  #  Kv Kw
      - ["1.K", "2.ROUNDS", -70]  #  KO KG KC
      - ["1.K", "2.s", -40]  #  Ks
      - ["1.K", "2.V", -70]  #  Ks
      - ["1.K", "2.T", -60]  #  Ks

      - ["1.L", "2.T", -110]  #  LT
      - ["1.L", "2.V", -130]  #  LV
      - ["1.L", "2.v", -80]  #  LV

      - ["1.P", "2.A", -90]  #  PA
      - ["1.P", "2.J", -100]  #  PJ
      - ["1.P", "2.X", -60]  #  PJ

      - ["1.R", "2.V", -70]  #  RV

      - ["1.T", "2.rounds", -90]  #  To Te
      - ["1.T", "2.A", -110]  #  TA
      - ["1.T", "2.a", -80]  #  TA
      - ["1.T", "2.ROUNDS", -40]  #  TO
      - ["1.T", "2.r", -60]  #  Tr
      - ["1.T", "2.u", -70]  #  Tu
      - ["1.T", "2.v", -80]  #  Tv Ty
      - ["1.T", "2.V", -40]  #  TV
      - ["1.T", "2.J", -100]  #  TJ
      - ["1.T", "2.s", -80]  #  Ts
      - ["1.T", "2.x", -70]  #  Tx

      - ["1.ROUNDS", "2.ROUNDS", -10] #  OO, OC
      - ["1.ROUNDS", "2.V", -70] #  OV, OW
      - ["1.ROUNDS", "2.A", -50] # DA OA
      - ["1.ROUNDS", "2.rounds", -20]
      - ["1.ROUNDS", "2.X", -60]

      - ["1.S", "2.v", -60]

      - ["1.U", "2.A", -60]

      - ["1.V", "2.ROUNDS", -80]
      - ["1.V", "2.rounds", -110]
      - ["1.V", "2.A", -140]
      - ["1.V", "2.i", -50] #  Vi
      - ["1.V", "2.a", -100]
      - ["1.V", "2.s", -110]
      - ["1.V", "2.r", -80]
      - ["1.V", "2.u", -90]
      - ["1.V", "2.J", -120]
      - ["1.V", "2.v", -100]
      - ["1.V", "2.V", -50]
      - ["1.V", "2.verticals", -80]
      - ["1.V", "2.J", -100]

      - ["1.X", "2.rounds", -50]
      - ["1.X", "2.u", -60]
      - ["1.X", "2.s", -40]
      - ["1.X", "2.t", -50]
      - ["1.X", "2.T", -40]
      - ["1.X", "2.V", -50]
      - ["1.X", "2.v", -90]
      - ["1.X", "2.ROUNDS", -60]

    malayalam:
      - ['്',"2.QUOTES", 125 ]
      - ['്',"2.PARANTHESIS", 100 ]
      - ['്',"!", 100 ]
      - ['്',"?", 125 ]
      - [['ത', 'ന', 'നു', 'ന്ന', "സ", 'ഗ'],"ം", -20 ]
      - [ "ം", ['ന', 'നു', 'നൂ', 'സ','സു', 'സൂ'], -20 ]
      - [['ത', 'സ', 'ന', 'നു', 'ന്ന'],["ക","കു","കൂ","കൃ"], -20 ]
      - [['ന്റ', 'ൻ്റ'], "്", 40 ]
      - [['ന്റ', 'ൻ്റ'], "ി", 40 ]
      - [['ന്റ', 'ൻ്റ'], "ീ", 40 ]
      - [["ഴ", "ഴു", "ഴൂ"], ['ക', 'കു', 'കൂ', 'ക്ക', 'ക്കു', 'ക്കൂ'], -30 ]
      - [["ഴ", "ഴു", "ഴൂ"], ['ച', 'ചൂ', 'ച്ച', 'ച്ചു', 'ച്ചൂ', 'ഛ'], -50 ]
  # calts:
  #   malayalam:
  #     - ['ന', "ി", 'wrap' ]
variablefonts:
  Malini:
    designspace: Malini.designspace
    stat:
      axes:
        - tag: opsz
          name: Optical Size
          values:
            - value: 10
              name: "10pt"
            - value: 12
              name: "12pt"
              flags: 2
            - value: 48
              name: "48pt"
        - tag: slnt
          name: Slant
          values:
            - value: 0
              name: Upright
              flags: 2
              linkedValue: -12
            - value: -12
              name: Italic
        - tag: wght
          name: Weight
          values:
            - value: 100
              name: Thin
            - value: 200
              name: ExtraLight
            - value: 300
              name: Light
            - value: 400
              name: Regular
              flags: 2
              linkedValue: 700
            - value: 500
              name: Medium
            - value: 600
              name: SemiBold
            - value: 700
              name: Bold
            - value: 800
              name: ExtraBold
            - value: 900
              name: Black
        - tag: wdth
          name: Width
          values:
            - value: 75
              name: Condensed
            - value: 87.5
              name: SemiCondensed
            - value: 100
              name: Normal
              flags: 2
            - value: 112.5
              name: SemiExpanded
            - value: 125
              name: Expanded

